ksuproject/urls.py
from django.contrib import admin
from django.urls import path
from website import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.SignupPage, name='signup'),
    path('', views.LoginPage, name='login'),
    path('logout/', views.LogoutPage, name='logout'),
    path('evaluation/', views.evaluation, name='evaluation'),
    path('evaluation/<int:pk>/edit/',
         views.edit_evaluation, name='edit_evaluation'),
    path('evaluation/<int:pk>/delete/',
         views.delete_evaluation, name='delete_evaluation'),
    path('evaluation_list/',
         views.evaluation_list, name='evaluation_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('student/', views.student, name='student'),
    path('evaluate/', views.evaluate, name='evaluate'),
    path('account/', views.account, name='account'),
    path('add_class/', views.add_class, name='add_class'),
    path('manage_class/', views.manage_class, name='manage_class'),
    path('add_student/', views.add_student, name='add_student'),
    path('manage_student/', views.manage_student, name='manage_student'),
    path('add_questionnaire/', views.add_questionnaire,
         name='add_questionnaire'),
]

website/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.


# class Rank(models.Model):
#     OPTIONS = (
#         ('Assoc Prof 1', 'Associate Professor I'),
#         ('Assoc Prof 2', 'Associate Professor II'),
#         ('Assoc Prof 3', 'Associate Professor III'),
#         ('Prof 1', 'Professor I'),
#         ('Prof 2', 'Professor II'),
#     )
#     faculty_rank = models.CharField(max_length=50, choices=OPTIONS)
#     # faculty_rank = models.CharField(max_length=100)

#     # def __str__(self):
#     #     return str(self.faculty_rank)


# class Course(models.Model):
#     OPTIONS = (
#         ('BSIT', 'Bachelor of Science in Information Technology'),
#         ('BSIS', 'Bachelor of Science in Information Systems'),
#         ('CompEng', 'Bachelor of Science in Computer Engineering'),
#         ('ComScie', 'Bachelor of Science in Computer Science'),
#     )
#     course_title = models.CharField(max_length=50, choices=OPTIONS)
#     # course_title = models.CharField(max_length=100)

#     # def __str__(self):
#     #     return str(self.course_title)


# class Subject(models.Model):
#     OPTIONS = (
#         ('DSA 1', 'Data Structure and Algortihm'),
#         ('SAD', 'System Analysis & Design'),
#         ('Prog I', 'Introduction to Programming'),
#     )
#     subject_title = models.CharField(max_length=50, choices=OPTIONS)
#     # subject_title = models.CharField(max_length=100)

#     # def __str__(self):
#     #     return str(self.subject_title)


# class Year(models.Model):
#     OPTIONS = (
#         ('Option 1', '2020'),
#         ('Option 2', '2021'),
#         ('Option 3', '2022'),
#         ('Option 4', '2023'),
#         ('Option 5', '2024'),
#         ('Option 6', '2025'),
#     )
#     year = models.CharField(max_length=50, choices=OPTIONS)
# year = models.CharField(max_length=100)

# def __str__(self):
#     return str(self.year)
# Create a model with a field to store the chosen option as an integer


class CourseEvaluation(models.Model):
    faculty_Lname = models.CharField(max_length=100)
    faculty_Fname = models.CharField(max_length=100)
    faculty_Mname = models.CharField(max_length=100)
    # faculty_rank = models.ForeignKey(Rank, on_delete=models.CASCADE)
    OPTIONS = (
        ('Assoc Prof 1', 'Associate Professor I'),
        ('Assoc Prof 2', 'Associate Professor II'),
        ('Assoc Prof 3', 'Associate Professor III'),
        ('Prof 1', 'Professor I'),
        ('Prof 2', 'Professor II'),
    )
    faculty_rank = models.CharField(max_length=50, choices=OPTIONS)

    # course_title = models.ForeignKey(Course, on_delete=models.CASCADE)
    OPTIONS = (
        ('BSIT', 'Bachelor of Science in Information Technology'),
        ('BSIS', 'Bachelor of Science in Information Systems'),
        ('CompEng', 'Bachelor of Science in Computer Engineering'),
        ('ComScie', 'Bachelor of Science in Computer Science'),

    )
    course_title = models.CharField(max_length=50, choices=OPTIONS)
    OPTIONS = (
        # 1st element is shown in the database while 2nd element shown in the dropdown menus.
        ('CC 118', 'CC 118'),
        ('CC 119', 'CC 119'),
        ('CC 120', 'CC 120'),
        ('CC 121', 'CC 121'),
        ('CC 122', 'CC 122'),
        ('CC 123', 'CC 123'),
        ('TECHNO  11', 'TECHNO  11'),
        ('PROF ED 14', 'PROF ED 14'),
    )
    subject_code = models.CharField(max_length=50, choices=OPTIONS)
    # subject_title = models.ForeignKey(Subject, on_delete=models.CASCADE)
    OPTIONS = (
        # 1st element is shown in the database while 2nd element shown in the dropdown menus.
        ('Information Assurance and Security 1',
         'Information Assurance and Security 1'),
        ('Social and Professional Issues', 'Social and Professional Issues'),
        ('Application Development and Emerging',
         'Application Development and Emerging'),
        ('System Integration and Architecture 1',
         'System Integration and Architecture 1'),
        ('System Integration and Architecture 1',
         'System Integration and Architecture 1'),
        ('Capstone Project and Research 1', 'Capstone Project and Research 1'),
        ('Technopreneurship', 'Technopreneurship'),
        ('Assessment of Learning 1', 'Assessment of Learning 1'),
    )
    subject_title = models.CharField(max_length=50, choices=OPTIONS)
    OPTIONS = (
        ('1st semester', '1st semester'),
        ('2nd semester', '2nd semester'),
        ('Summer Class', 'Summer Class'),
    )
    semester = models.CharField(max_length=100, choices=OPTIONS)
    # year = models.ForeignKey(Year, on_delete=models.CASCADE)
    OPTIONS = (
        ('2020', '2020'),
        ('2021', '2021'),
        ('2022', '2022'),
        ('2023', '2023'),
        ('2024', '2024'),
        ('2025', '2025'),
    )
    year = models.CharField(max_length=50, choices=OPTIONS)
    student_ID = models.CharField(max_length=100)
    student_name = models.CharField(max_length=100)
    OPTIONS = (
        ('BSIT', 'Bachelor of Science in Information Technology'),
        ('BSIS', 'Bachelor of Science in Information Systems'),
        ('CompEng', 'Bachelor of Science in Computer Engineering'),
        ('ComScie', 'Bachelor of Science in Computer Science'),
    )
    student_course = models.CharField(max_length=100, choices=OPTIONS)
    communication = models.IntegerField()
    delivery = models.IntegerField()
    engagement = models.IntegerField()
    responsiveness = models.IntegerField()
    feedback = models.IntegerField()
    inclusiveness = models.IntegerField()
    technology = models.IntegerField()
    critical_thinking = models.IntegerField()
    motivation = models.IntegerField()
    satisfaction = models.IntegerField()
    comments = models.CharField(max_length=200)

    @property
    def total_average(self):
        return sum([self.communication, self.delivery, self.engagement, self.responsiveness, self.feedback,
                    self.inclusiveness, self.technology, self.critical_thinking, self.motivation, self.satisfaction]) / 10

    def __str__(self):
        return f"{self.course_title} - {self.faculty_Lname} ({self.semester} {self.year})"

    # def clean(self):
    #     try:
    #         faculty_rank = Rank.objects.get(id=self.faculty_rank_id)
    #     except Rank.DoesNotExist:
    #         raise ValidationError('Invalid faculty rank id')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
        # Save the CourseEvaluation object

website/forms.py
from .models import CourseEvaluation  # , Rank, Course, Subject, Year
from django import forms


class CourseEvaluationForm(forms.ModelForm):
    communication = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    delivery = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    engagement = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    responsiveness = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    feedback = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    inclusiveness = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    technology = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    critical_thinking = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    motivation = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )
    satisfaction = forms.TypedChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'),
                 (4, '4'), (5, '5')],
        widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
        coerce=int
    )

    class Meta:
        model = CourseEvaluation
        fields = ['faculty_Lname', 'faculty_Fname', 'faculty_Mname', 'faculty_rank', 'course_title', 'subject_code', 'subject_title', 'semester', 'year', 'student_ID', 'student_name', 'student_course', 'communication', 'delivery', 'engagement', 'responsiveness',
                  'feedback', 'inclusiveness', 'technology', 'critical_thinking', 'motivation', 'satisfaction', 'comments']


# class RankForm(forms.ModelForm):
#     class Meta:
#         model = Rank
#         fields = ['faculty_rank']


# class CourseForm(forms.ModelForm):
#     class Meta:
#         model = Course
#         fields = ['course_title']


# class SubjectForm(forms.ModelForm):
#     class Meta:
#         model = Subject
#         fields = ['subject_title']


# class YearForm(forms.ModelForm):
#     class Meta:
#         model = Year
#         fields = ['year']

        # def __init__(self, *args, **kwargs):
        #     super().__init__(*args, **kwargs)
        #     self.fields['faculty_rank'].queryset = Rank.objects.all()
        #     self.fields['course_title'].queryset = Course.objects.all()
        #     self.fields['subject_title'].queryset = Subject.objects.all()
        #     self.fields['year'].choices = [
        #         (year, year) for year in range(2000, 2051)]

website/views.py
# from .forms import RankForm, CourseForm, SubjectForm, YearForm
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import CourseEvaluation
from .forms import CourseEvaluationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.


@login_required(login_url='login')
def HomePage(request):
    return render(request, 'index.html')


def SignupPage(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')

        if pass1 != pass2:
            return HttpResponse("Your password and confrom password are not Same!!")
        else:

            my_user = User.objects.create_user(uname, email, pass1)
            my_user.save()
            return redirect('login')
    return render(request, 'signup.html')

# Create your views here.


def LoginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        pass1 = request.POST.get('pass')
        user = authenticate(request, username=username, password=pass1)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            return HttpResponse("Username or Password is incorrect!!!")

    return render(request, 'login.html', {'user': request.user})


def LogoutPage(request):
    logout(request)
    return redirect('login')


def evaluation(request):
    if request.method == 'POST':
        form = CourseEvaluationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('evaluation_list')
    else:
        form = CourseEvaluationForm()
    return render(request, 'evaluation.html', {'form': form})


def edit_evaluation(request, pk):
    template_name = 'evaluation.html'
    success_url = reverse_lazy('evaluation_list')
    evaluation = get_object_or_404(CourseEvaluation, pk=pk)
    if request.method == 'POST':
        form = CourseEvaluationForm(request.POST, instance=evaluation)
        if form.is_valid():
            form.save()
            return redirect('evaluation_list')
    else:
        form = CourseEvaluationForm(instance=evaluation)
    return render(request, template_name, {'form': form})


def delete_evaluation(request, pk):
    template_name = 'delete_evaluation.html'
    success_url = reverse_lazy('evaluation_list')
    evaluation = get_object_or_404(CourseEvaluation, pk=pk)
    if request.method == 'POST':
        evaluation.delete()
        return redirect('evaluation_list')
    return render(request, template_name, {'evaluation_list': evaluation})


def evaluation_list(request):
    evaluations = CourseEvaluation.objects.all()
    return render(request, 'evaluation_list.html', {'evaluations': evaluations})


def dashboard(request):
    return render(request, 'index.html')


def student(request):
    return render(request, 'student.html')


def evaluate(request):
    if request.method == 'POST':
        # rank_form = RankForm(request.POST)
        # course_form = CourseForm(request.POST)
        # subject_form = SubjectForm(request.POST)
        # year_form = Year
        form = CourseEvaluationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('evaluation_list')
    else:
        # , RankForm(), CourseForm(), SubjectForm(), YearForm()
        form = CourseEvaluationForm()
    return render(request, 'evaluation.html', {'form': form, })
    # 'rank_form': rank_form, 'course_form': course_form,
    # 'subject_form': subject_form, 'year_form': year_form,


# def my_view(request):
#     rank_form = RankForm()
#     course_form = CourseForm()
#     subject_form = SubjectForm()
#     year_form = YearForm()
#     return render(request, 'evaluation.html', {
#         'rank_form': rank_form,
#         'course_form': course_form,
#         'subject_form': subject_form,
#         'year_form': year_form,
#     })
#     if request.method == 'POST':
#         rank_form = RankForm(request.POST)
#         course_form = CourseForm(request.POST)
#         subject_form = SubjectForm(request.POST)
#         year_form = Year


def account(request):
    return render(request, 'account.html')


def add_class(request):
    return render(request, 'add_class.html'),


def add_questionnaire(request):
    return render(request, 'add_questionnaire.html'),


def add_student(request):
    return render(request, 'add_student.html'),


def manage_class(request):
    return render(request, 'manage_class.html'),


def manage_student(request):
    return render(request, 'manage_student.html'),

website/templates/add_class.html
{% load static %}
<!DOCTYPE html><!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Add Class</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- FontAwesome JS-->
    <script defer src="assets/plugins/fontawesome/js/all.min.js"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="assets/css/portal.css">

</head> 

<body class="app">
    {% include "__bits\_navbar.html"%}
    {% include "__bits\_sidebar.html"%}
    <div class="app-wrapper">
	
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">			    
			    <h1 class="app-page-title text-success"><span class="nav-icon"><i class="fa fa-school"></i></span> Add Class</h1>
			    <hr class="mb-4">
                <div class="row g-4 settings-section">
	                <div class="col-12 col-md-8">
		                <div class="app-card app-card-settings shadow-sm p-4">
						    
						    <div class="app-card-body">
							    <form class="settings-form" method="post">
									{% csrf_token %}
									<div class="mb-3">
									    <label for="setting-input-2" class="form-label">Class Code</label>
									    <input type="text" class="form-control" id="setting-input-2" value="" required>
									</div>
								    <div class="mb-3">
									    <label for="setting-input-3" class="form-label">Instructor Name</label>
									    <input type="test" class="form-control" id="setting-input-3" value="" required>
									</div>
								    <div class="mb-3">
									    <label for="setting-input-3" class="form-label">Class</label>
									    <input type="text" class="form-control" id="setting-input-3" value="" required>
									</div>
								    <div class="mb-3">
									    <label for="setting-input-3" class="form-label">Subject</label>
									    <input type="text" class="form-control" id="setting-input-2" value="" required>
									</div>
								    <div class="mb-3">
									    <label for="setting-input-3" class="form-label">No. of Students</label>
									    <input type="number" class="form-control" id="setting-input-2" value="" required>
									</div>
									<button type="submit" class="btn app-btn-primary" >Save</button>
							    </form>
						    </div><!--//app-card-body-->
						    
						</div><!--//app-card-->
	                </div>
                </div><!--//row-->

			    <hr class="my-4">
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
	    
    </div><!--//app-wrapper-->    					

 
    <!-- Javascript -->          
    <script src="assets/plugins/popper.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>  
    
    <!-- Page Specific JS -->
    <script src="assets/js/app.js"></script> 

</body>
</html> 

website/templates/delete_evaluation.html
{% extends 'home.html' %}

{% block content %}
<style>
    .delbtn{
        
    }
</style>
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this survey rating?</p>
  <form method="post">
    {% csrf_token %}
    <input class = "delbtn" type="submit" value="Yes, delete">
    <a href="{% url 'evaluation_list' %}">Cancel</a>
  </form>
{% endblock %}

website/templates/evaluate.html
{% comment %} {% load static%}

<body class="app">  {% endcomment %}
    {% comment %} {% include '__bits\_navbar.html'%} {% endcomment %}
    {% comment %} {% include '__bits\_studentsidebar.html'%}
    {%block content %}
    <div class="app-wrapper">
	    
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">
			    <img src="{% static 'images/ksuniversity.png' %}" alt="lol" style="width: 125px;">
			    <h1 class="app-page-title"><span class="nav-icon"><i class="fa fa-file"></i></span> KSU Faculty Evaluation Survey</h1>
			    <div class="row g-4 mb-4">
	                <div class="col-12 col-md-12">
		                <div class="app-card app-card-settings shadow-sm p-4">
						    <div class="app-card-body">
							    <form method="post">
                                    {% csrf_token %}
									<div class="mb-3">
									    <label for="setting-input-2" class="form-label"><h4>Faculty Name</h4></label>
									  
                                            <div class= 'rating-container'>
                                              <label for="id_faculty_Lname">Last Name:</label>
                                              {{form.faculty_Lname}}
                                          </div>
                                            <div class= 'rating-container'>
                                                <label for="id_faculty_Fname">First Name:</label>
                                                {{form.faculty_Fname}}
                                            </div>
                                              <div class= 'rating-container'>
                                                <label for="id_faculty_Mname">Middle Name:</label>
                                                {{form.faculty_Mname}}
                                            </div>
                                            <div class= 'rating-container'>
                                              <label for="id_faculty_rank">Rank:</label>
                                              {{form.faculty_rank}}
                                            </div>
                                    
						       </div><!--//app-card-body-->
						</div><!--//app-card-->
	                </div>
	                <div class="col-12 col-md-12">
		                <div class="app-card app-card-settings shadow-sm p-4">
						    <div class="app-card-body">
                                <hr>
    <h4>Course</h4>
    <div class= 'rating-container'>
        <label for="id_course_title">Course title:</label>
        {{form.course_title}}
    </div>
    <div class= 'rating-container'>
      <label for="id_subject_title">Subject:</label>
      {{form.subject_title}}
  </div>
    <div class= 'rating-container'>
        <label for="id_semester">Semester:</label>
        {{form.semester}}
    </div>
    <hr>
    <div class= 'rating-container'>
        <label for="id_year">Year:</label>
        {{form.year}}
    </div>
    <br>
    
    <div class= 'rating-container'>
        <label for="id_evaluator">Evaluator:</label>
        {{form.evaluator}}
    </div>
   <br>
    <fieldset class="border border-info p-2 w-100">
        <legend  class="w-auto">Rating Legend</legend>
        <p>5 = Strongly Agree, 4 = Agree, 3 = Uncertain, 2 = Disagree, 1 = Strongly Disagree</p>
     </fieldset><br> {% endcomment %}
     {% comment %} <fieldset class="border border-info p-2 w-100"> {% endcomment %}
    {% comment %} <label for="setting-input-2" class="form-label bg-info">Category</label>
    <hr>                      
    <p>1. How well did the faculty member communicate the course objectives and expectations at the beginning of the course?</p>
     <div>
      {% for radio in form.communication %}
            {{ radio }}
          {% endfor %} {% endcomment %}
    {% comment %} {{form.communication}} {% endcomment %}
     {% comment %} </div>
     <p>2. How effective was the faculty member in delivering the course material and explaining complex concepts?</p>
     <div>
      {% for radio in form.delivery %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.delivery}} {% endcomment %}
     {% comment %} </div>
     <p>3.How well did the faculty member engage with the students during the course?</p>
     <div>
      {% for radio in form.engagement %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.engagement}} {% endcomment %}
     {% comment %} </div>
     <p>4.Did the faculty member respond to student questions and concerns in a timely manner?</p>
     <div>
      {% for radio in form.responsiveness %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.responsiveness}} {% endcomment %}
     {% comment %} </div>
     <p>5.Did the faculty member provide helpful feedback on assignments and exams in a timely manner?</p>
     <div>
      {% for radio in form.feedback %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.feedback}} {% endcomment %}
     {% comment %} </div>
     <p>6.Did the faculty member create a welcoming and inclusive classroom environment?</p>
     <div>
      {% for radio in form.inclusiveness %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.inclusiveness}} {% endcomment %}
     {% comment %} </div>
     <p>7. Did the faculty member effectively use technology in the course?</p>
     <div>
      {% for radio in form.technology %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.technology}} {% endcomment %}
     {% comment %} </div>
     <p>8. Did the faculty member promote critical thinking and intellectual curiosity among students?</p>
     <div>
      {% for radio in form.critical_thinking %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.critical_thinking}} {% endcomment %}
     {% comment %} </div>
     <p>9. Did the faculty member effectively challenge and motivate students to learn?</p>
     <div>
      {% for radio in form.motivation %}
            {{ radio }}
          {% endfor %} {% endcomment %}
        {% comment %} {{form.motivation}} {% endcomment %}
     {% comment %} </div>
     <p>10. Overall, how satisfied were you with the faculty member's performance in the course?</p>
     <div>
      {% for radio in form.satisfaction %}
            {{ radio }}
          {% endfor %} {% comment %} note: this for loop displays radio button horizontally {% comment %} {% endcomment %}
        {% comment %} {{form.satisfaction}} {% endcomment %}
     {% comment %} </div>
     <hr>
     &nbsp
     <div class= 'rating-container'>
        <p><label for="id_comments">Comments:</label></p>
        {{form.comments}}
     </div>
     <button style="color:white; border-radius:10%; background-color: black;" type="submit">Submit</button>
    </form>
						    </div><!--//app-card-body-->
						    
						</div><!--//app-card-->
	                </div>
			    </div><!--//row-->
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
	    
    </div><!--//app-wrapper-->    					

 
    <!-- Javascript -->          
    <script src="{% static 'plugins/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>  

    <!-- Charts JS -->
    <script src="{% static 'plugins/chart.js/chart.min.js' %}"></script> 
    <script src="{% static 'js/index-charts.js' %}"></script> 
    
    <!-- Page Specific JS -->
    <script src="{% static 'assets/js/app.js' %}"></script> 
{% endblock %}
</body>
</html>  {% endcomment %}

website/templates/home.html
<body class="app">   	
 {% include '__bits\_navbar.html'%}
 {% include '__bits\_sidebar.html'%}
  <div class="app-wrapper">
	    {% block content %}

      {% endblock %}
    

website/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% comment %} {% block title %}SignupPage{% endblock %} {% endcomment %}
 
    {% comment %} <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> {% endcomment %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/signuppage.css'%}">
    <!--Stylesheet-->
</head>
<body class="body" style="background-color:rgba(6, 124, 139, 0.808);">
    {% comment %} <div class="background">
        <img id='iamg' src="{% static 'images/ksuniversity.png' %}" alt="ksupic">
    </div> {% endcomment %}
    <form class="forms" action="" method="post">
        {% csrf_token %} 
        <h3>Signup Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Username" name="username" id="username">

        <label for="email">Email</label>
        <input type="email" placeholder="Email or Phone" name="email" id="email">

        <label for="password1">Password</label>
        <input type="password" placeholder="Password" id="password1" name="password1">

        <label for="password2">Confirm Password</label>
        <input type="password" placeholder="Confirm Password" id="password2" name="password2">
        <button type="submit">Signup</button>
        <a href="{% url 'login' %}" >I have already an account</a>
   
    </form>

</body>
</html>